### ISSUE TITLE
Allow `head` request method only for good bots option

### ISSUE THREAD

**Issue by summer-cms** [summer-cms/sc-security-module#537]
### Enhancement idea

- [x] Allow `head` request method only for good bots option. The idea is to block ban bots performing quick web scans on website lists. By default the firewall allows all `head` requests; but can be set to block all these requests - however, some good bots use the `head` request method. This way the end user can fine tune things.
- [x] Update frontend firewall
- [x] Update backend firewall
- [x] Update settings section

**Comment by ayumi-cloud** [comment]
add `is_numeric`

**Comment by ayumi-cloud** [comment]
Update settings section

**Comment by ayumi-cloud** [comment]
update regex settings val

**Comment by ayumi-cloud** [comment]
reset ua section back to normal

**Comment by ayumi-cloud** [comment]
https://www.postman.com/

**Comment by ayumi-cloud** [comment]
https://octobercms.com/support/article/rn-13
